/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bouncysteve' at '17/02/16 20:31' with Gradle 2.6
 *
 * @author bouncysteve, @date 17/02/16 20:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
